dist: trusty
sudo: required

before_script: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - chmod 0777 ./node_modules/.bin/mocha
  
script: xvfb-run make test

language: node_js
node_js: 
- "6.1.0"
sudo: required

  
addons:
- firefox: latest
   apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

     
  
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver.exe

# configure which branches to run
branches:
  # whitelist
  only:

    - Gooogle
    - master
    - /^deploy-.*$/ # regex ok
  # blacklist
  except:
    - TravisIntegration
    - TestRepo 




