dist: trusty
sudo: required

before_script: 
  - chmod 0777 ./node_modules/.bin/mocha
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - "wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar"
  - "java -jar selenium-server-standalone-2.53.0.jar > /dev/null &"
  - sleep 3
  
language: node_js
node_js: 
- "6.1.0"
sudo: required

  
addons:
- firefox: "49.0"
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
- chrome : stable
     
  
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver.exe

# configure which branches to run b
branches:
  # whitelist
  only:

    - Gooogle
    - master
    - /^deploy-.*$/ # regex ok
  # blacklist
  except:
    - TravisIntegration
    - TestRepo   




