/**
Created By QA Source
 */

module.exports={
   
	//crossBrowserTesting : 'Chrome,Firefox',
	crossBrowserTesting : 'Firefox',
    waitForConditionTimeout: '90000',
    team : 'smoke-automate', //staging
    teamSanity : 'sanity-automate',
    teamRegression :'regression-automate',
    switchTeam : 'smoke-automate',//'sanity-automate1',
    //team : 'occt18', //production
    email: 'elgon_qa1@testmailaccount.com',
    Slackemail2: 'elgon_qa2@testmailaccount.com',
    emailForSignInWithEmail : 'elgon3412@gmail.com',
    teamForSignInWithEmail : 'Smoke-AutomateEmail',
    password: 'Welcome1234!',
    newDeck: 'New Deck',
    comment : 'test comment',
    threadCommentCount : '3', //it will create for loop which defines length of comment thread and count of comments
    generalChannel : 'general',
    privateToMe : 'Private to Me',
    timeout : '50000',
    wait : '900000',
    pasteUrl : 'https://staging.pasteapp.com', //staging
   // pasteUrl : 'https://pasteapp.com', //production
    text : 'Text slide created',
    publicChannel :'public',
    User2 : 'Elgon 2 Elgon',
    slackUrl : 'https://slack.com/',
    slackTeamEmail : 'elgonqa.qasource5@gmail.com',
    gmail : 'https://accounts.google.com/',
    gmailUser : 'elgonqa.qasource5@gmail.com',
    gmailPassword : 'Frt5Dk5%F{6]r',
    fullName : 'QaTester',
    useOfSlackTeam : 'Work',
    gmailUser2 : 'elgonqa.qasource6@gmail.com',
    gmailPassword2 : 'Uhg76k2sfv@$',
    upgradeTeamMMessage : 'has reached a limit of the Free plan. Upgrade now for:',
    invalidLoginMessage : 'Sorry, you entered an incorrect email address or password.',
    teamHavingUser1and2 : 'slacktestcase2',
    teamHavingUser3 : 'slacktestcase2',
    emailUser3 : 'elgon_qa3@testmailaccount.com',
    slackUser2 : 'qwe',
    thumbsUpEmoji : 'ReactionThumbsUp',
    thumbsDownEmoji : 'ReactionThumbsDown',
    clapEmoji : 'ReactionClap',
    flagEmoji : 'ReactionFlag',
    checkEmoji : 'ReactionCheck',
    slackEmail3  : 'elgonqa.qasource4@gmail.com',
    slackEmail3Password : 'ZzKux5%F)[',
    invitationEmails : 'elgonqa.qasource4@gmail.com', 
    cardNumberForProBilling: '4242424242424242',
    mmddForProBilling : '1125',
    cvcForProBilling: '123',
    FreePlan : 'Free',
    ProPlan : 'Pro',
	user4Name : 'qa4',
	email4: 'elgon_qa4@testmailaccount.com',
    paste : 'Paste',
    smokechannel : 'smoke',
    numberOfdecksForFreeUser : '3',
    privateChannel : 'private_01',
    videoLink : 'https://vimeo.com/37254322',
    imageLink : 'https://www.whoa.in/20130627-Whoa/Natural-Waterfall-Hd-Wallpaper-For-Mobile.jpg',
    addLink : 'Add a Link',
    behanceUpload :'Behance',
    codepenUpload :'Codepen',
    figmaUpload :'Figma',
    message : 'You can add up to 4 assets per slide.',
    giphy : 'Giphy',
    gmailLink : 'https://mail.google.com/mail/u/0/#inbox',
    publicChannel1 : 'public',
    privateChannel1 : 'private',
    stripeName : 'qatester',
    stripeStreet :	'gurbux',
    stripeCity :	'chandigarh',
    stripePostcode :	'147001',
    shadowAsset : 'Shadow',
    noneOption : 'None',
    largeText : 'h1',
    smallText : 'body',
    mediumText : 'h2',
    orderedList : 'numbered',
    unorderedList : 'bulleted',
    code  : 'code',
    bold : 'weight: 700',
    italic : 'style: italic',
    user1Name : 'qa1',
    assignmentMessage : ' assigned a slide to you',
	channelSanity : 'sanity',
    shareMessage : ' shared a deck',
    team2 : '25-may',//'smoke-automate-4-11',
    sortedTeam : 'deck-order',
    deckInTeam  : 'Alphabetical',
   starterTeamPlan :'Starter',
   starterTeamClass :'starter',
    teamTeamPlan :'Team',
    teamTeamClass :'team',
    fileUploadTeam : 'uploadfile',
    oneTimePublicChannel : 'temppublicchannel',
    oneTimePrivateChannel : 'tempprivatechannel',
    placeholderInPublicChannels : 'It’s easy to work on a deck with your team when you create it as part of a Slack channel. You can share your updates directly to the channel. You can mention and assign teammates to slides, and they will be notified through Slack. Get started by choosing ‘New Deck’ above.',
    placeholderInPrivateChannels : 'It’s easy to work privately on a deck with your team when you create it as part of a private Slack channel. Your deck will only be visible to the people in your private Slack channel unless you share the link more broadly. You can share your updates directly to the channel. You can mention and assign teammates to slides, and they will be notified through Slack. Get started by choosing ‘New Deck’ above.',
    googleLink : 'https://www.google.com/?gws_rd=ssl',
    dropboxUpload : 'Dropbox',
    dropboxUserName : 'elgon3412@gmail.com',
    dropboxPassword : 'test123',
    pdfFile : ' Get Started with Dropbox Paper.url',//'Get Started with Dropbox.pdf',
    updatedTeamName : 'updateteamname1',
    googleDocsUpload : 'Google Docs',
    shortwait : '3000',
    updateTeam : 'updateteamname',
    boxUpload : 'Box',
    boxUserName : 'elgon3412@gmail.com',
    boxPassword : 'Welcome1234!',
    boxImageFile : 'Image-1.jpg',
    oneDriveUpload : 'OneDrive',
    oneDriveFileUpload : 'Getting started with OneDrive.pdf',
    googleDriveUpload : 'Google Drive',
    googleDriveImageFile : 'Image.jpg',
    landscapeImage : 'https://i-cdn.phonearena.com/images/articles/280797-thumb/2-to-1-wallpapers-header.jpg',
    supportArticles : 'Paste by FiftyThree Help',
    supportArticlesUrl :'http://support.pasteapp.com/',
    //pasteMobileApp : 'Paste by FiftyThree on the App Store',
    pasteMobileAppUrl : 'https://itunes.apple.com/app/id1259981327?mt=8',
    termsOfService : 'Terms of Service | FiftyThree',
    termsOfServiceUrl: 'https://www.fiftythree.com/legal/terms',
    unsplash : 'Unsplash',
    framer : 'Framer',
    googleDocs : 'Google Docs',
    googleMaps : 'Google Maps',
    createTeam : 'smoke',
    allTeamDecks : 'All Decks',
    arcieveChannel : 'archivechannel',
    typeOfChannel: 'Archived Channels',
    verySmallTimout :'500',
    createTeamForSanity: 'sanity',
    reorderFrom : '0',
    reorderTo : '1',
    infogram : 'Infogram',
    instagram : 'Instagram',
    invision : 'Invision',
    marvel : 'Marvel',
    sketchfab : 'Sketchfab',
    spotify : 'Spotify',
    trello : 'Trello',
    twitter : 'Twitter',
    vimeo : 'Vimeo',
    youtube : 'YouTube',
    pathInInsertIcon : '2',
    pathInDuplicateIcon : '3',
    pathInDeleteIcon : '5',
    viewingStatus : 'Viewing...',
    PasteAppHelpPageData : 'This app is only available on the App Store for iOS devices',
    exportPDF : 'Export Deck as PDF',
    embedDeck : 'Embed Deck',
    deckDuplication : 'Duplicate Deck',
    deckDeletion : 'Delete Deck',    
    
};